# This is a basic workflow to help you get started with Actions

name: Scrap

# Controls when the action will run. 
on:
  schedule:
    - cron: "15,45 12-17 * * 1-5"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scrap:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: "Checkout repository"

      - uses: actions/setup-python@v2
        name: "Setup Python"
        with:
          python_version: "3.9"

      - name: "Install dependencies"
        run: "pip install -U pip requests lxml"

      - name: "Scrapy scrap"
        run: "python happykaktus.py"
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHATID: ${{ secrets.TELEGRAM_CHATID }}

      - name: "Commit last state"
        run: |
          git config user.name "GitHub Action"
          git config user.email "robot@github.invalid"
          git add lastitem.html || true
          git commit -m "Update last item (autocommit)" || true
